# Copyright © 2022  Neeraj Singhal
# All rights reserved
# Info: https://bazel.build/build/style-guide

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)